% MEEdrift_annotate_DMPA_BPP_plots

set (gca, 'Fontname', 'Times')

text (...
	'Position', [AxisMax+1.0, -(AxisMax-1.0), 0],...
	'HorizontalAlignment', 'left', 'VerticalAlignment', 'top',...
	'Fontname', 'Times', 'FontSize', 9,...
	'string', sprintf ('GyroPeriod %8.6f s', abs (gyroPeriod)) );

if strcmp (PlotView, '2D')
	strCoordSys = 'BPP';
	xlabel ('BPPx (m)', 'Position', [  0.00           -(AxisMax+0.50)  AxisMax ]); % 2D X-Y display
	ylabel ('BPPy (m)', 'Position', [ -(AxisMax+0.50)  0.00            AxisMax ]);
	zlabel ('BPPz (m)', 'Position', [  (AxisMax+0.50) -AxisMax        -0.25 ], 'Rotation', 0);
	text (...
		'Position', [AxisMax+1.0, -(AxisMax-1.0), 0],...
		'HorizontalAlignment', 'left', 'VerticalAlignment', 'top',...
		'Fontname', 'Times', 'FontSize', 9,...
		'string', sprintf ('GyroPeriod %8.6f s', abs (gyroPeriod)) );
else
	strCoordSys = 'DMPA';
	xlabel ('DMPAx (m)', 'Position', [ 0.0             (AxisMax+0.50) -(AxisMax+0.50)    ]); % 3D display
	ylabel ('DMPAy (m)', 'Position', [ (AxisMax+0.50) -0.25           -(AxisMax+0.50)    ]);
	zlabel ('DMPAz (m)', 'Position', [ (AxisMax+0.50) -(AxisMax+0.50) -0.25 ], 'Rotation', 0);
	text (...
		'Position', [ -2.0, AxisMax+4.0, -AxisMax ],...
		'HorizontalAlignment', 'left', 'VerticalAlignment', 'top',...
		'Fontname', 'Times', 'FontSize', 9,...
		'string', sprintf ('GyroPeriod %8.6f s', abs (gyroPeriod)) );
end

strBeamTime = char(spdfencodett2000(centerBeam_t2k));
strBeamTime = strBeamTime (1:23);
title_ = ( { [ strCoordSys, ' coordinate system, B = [',...
						  num2str(round (centerBeamB (1))),',',...
						  num2str(round (centerBeamB (2))),',',...
						  num2str(round (centerBeamB (3))), '] nT' ]; ...
						 [ 'MMS', obsID, ' ', strBeamTime ]; ...
						 ['EDI beam times within ± ', num2str(beamsInWindow), ' records of center beam']; ...
						 ['MEEdrift ', dotVersion, '   ', datestr(now, 'yyyy-mm-dd HH:MM:SS') ]; ...
						 [] } );
title (title_, 'Fontname', 'Times');

if length (p) == 9 % v1504
	legend (hDMPA__BPP_legendAxes, p, ... % hDMPA_plotElements, ...
		'GDU plane', 'BPP plane', 'GDU1', 'GDU2', 'Beams', 'EDI B (unit)', 'EDI E (unit)', 'EDI S*', 'EDP E (unit)', 'Location', 'EastOutside');
		%p1,          p2           p3      p4      p5       p6           p7              p8                  p9           , ...
end
% if length (p) == 7
% 	legend    p1,          p2      p3      p4                       p5                   p6              p7      , ...
% 	legend (p, 'GDU plane', 'GDU1', 'GDU2', 'Beams, solid & dashed', 'EFW 3D DMPA (unit)', 'ExB Drift S*', 'Calc Perp S*', ...
% 					'Location', 'NorthEastOutside');
% end
% if length (p) == 9
% 	legend    p1,          p2      p3      p4                       p5  sq               p6  ci          p7 tri          p8   sqsol        ,  p9 cisol    ...
% 	legend (p, 'GDU plane', 'GDU1', 'GDU2', 'Beams, solid & dashed', 'EFW 3D BPP (norm)', 'ExB Drift S*', 'Calc Perp S*', 'MP EDI E3D BPP, Ê', 'MP EDI S*', ...
% 					'Location', 'NorthEastOutside');
% end
% if length (p) == 12
% 	legend    p1,          p2      p3      p4                       p5  sq               p6  ci          p7 tri          p8   sqsol        ,  p9 cisol    ...
% 	          p10                 p11         P12
% 	legend (p, 'GDU plane', 'GDU1', 'GDU2', 'Beams, solid & dashed', 'EFW 3D DMPA (unit)', 'ExB Drift S*', 'Calc Perp S*', 'MP EDI E3D BPP, Ê', 'MP EDI S*', ...
% 						 'Proxy E3D BPP, Ê', 'Proxy S*', 'Proxy Perp S*', ...
% 						 'Location', 'NorthEastOutside');
% end

legend ('boxoff');

if PlotHoldOff
	hold off
end
